### ISSUE TITLE
Is there any way to bypass this restriction without custom proxies? Like Google, Cloudflare DNS?

### ISSUE THREAD

**Issue by anburocky3** [qurbat/act-censorship#4]

**Comment by anburocky3** [comment]
Even https bypass doesn't works in ACT.

**Comment by qurbat** [comment]
I am currently not aware of any techniques that are known to be fully resistant to potential censorship. As for the second point, the `https://` method had previously been documented to work, though the example is a little dated from [December 2019.](https://twitter.com/squeal/status/1211302320387981312)

**Comment by qurbat** [comment]
@captn3m0 @swapneelp Would you have any insight on this?

**Comment by anburocky3** [comment]
Act is pretty smart at this, they drop the connection when we try to access it with `https`

**Comment by anburocky3** [comment]
Accessing: `http://yts.mx`

![image](https://user-images.githubusercontent.com/15264938/133905479-59e0ada1-5eb4-4379-98fe-ae50bb775958.png)

Accessing with `https://yts.mx`: 

![image](https://user-images.githubusercontent.com/15264938/133905491-0ff6e820-0a09-4d78-bf9d-94928d5c9728.png)

**Comment by Jrchintu** [comment]
Currently, many isp in india are using dpi based blocking. It can be evaded by tools that manipulate host header or client hello. https://github.com/zhenyolka/DPITunnel-android is an example for android and for linux https://github.com/zhenyolka/DPITunnel-cli . There are also tools like goodbyedpi etc.

**Comment by qurbat** [comment]
Thanks @bugaddr! Closing this issue.
